name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "**/*.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "**/*.md"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
